-- Run this SQL in your Supabase SQL Editor.

-- Users Table
CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name TEXT NOT NULL,
    email TEXT UNIQUE NOT NULL,
    organization TEXT,
    password_hash TEXT NOT NULL,
    role TEXT DEFAULT 'admin',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc', now()),
    last_login TIMESTAMP WITH TIME ZONE
);

-- Cloud Accounts Table
CREATE TABLE IF NOT EXISTS cloud_accounts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    provider TEXT NOT NULL,
    alias TEXT NOT NULL,
    access_key TEXT,
    secret_key TEXT,
    region TEXT DEFAULT 'us-east-1',
    status TEXT DEFAULT 'active',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc', now())
);

-- Scan Results Table
CREATE TABLE IF NOT EXISTS scan_results (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    account_id BIGINT NOT NULL,
    scan_name TEXT,
    provider TEXT,
    status TEXT DEFAULT 'pending',
    categories TEXT,
    total_findings INTEGER DEFAULT 0,
    critical_count INTEGER DEFAULT 0,
    high_count INTEGER DEFAULT 0,
    medium_count INTEGER DEFAULT 0,
    low_count INTEGER DEFAULT 0,
    risk_score INTEGER DEFAULT 100,
    risk_grade TEXT DEFAULT '?',
    suppressed_fp INTEGER DEFAULT 0,
    error_message TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc', now()),
    completed_at TIMESTAMP WITH TIME ZONE
);

-- Findings Table
CREATE TABLE IF NOT EXISTS findings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    scan_id BIGINT NOT NULL REFERENCES scan_results(id) ON DELETE CASCADE,
    resource_type TEXT,
    resource_id TEXT,
    check_name TEXT,
    severity TEXT,
    description TEXT,
    recommendation TEXT,
    compliance TEXT,
    status TEXT DEFAULT 'open',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc', now())
);

-- Reports Table
CREATE TABLE IF NOT EXISTS reports (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    scan_id BIGINT NOT NULL,
    report_name TEXT,
    format TEXT,
    filename TEXT,
    filepath TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc', now())
);

-- Breach Checks Table
CREATE TABLE IF NOT EXISTS breach_checks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    check_type TEXT,
    identifier TEXT,
    result TEXT,
    found SMALLINT DEFAULT 0,
    breach_count INTEGER DEFAULT 0,
    checked_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc', now())
);
